name: Trigger Central Pipeline on PR Events

on:
  pull_request:
    types:
      - opened        # Triggered when a PR is created (opened)
      - closed        # Triggered when a PR is merged (closed)
      - synchronize   # Triggered when a PR is updated (new commits)
    branches:
      - main  # You can modify this as per your branch names----

jobs:
  trigger_central_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Central Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: Srijan-DevOpsEr/Central-build
          event-type: pr_event
          client-payload: |
            {
              "triggered_by": "${{ github.repository }}",
              "pr_event": "${{ github.event.action }}",
              "pr_number": "${{ github.event.pull_request.number }}",
              "commit_sha": "${{ github.sha }}",
              "branch": "${{ github.head_ref }}"
            }

      - name: Add central pipeline link to summary
        run: |
          echo "🔗 [View Central Pipeline Runs](https://github.com/Srijan-DevOpsEr/Central-build/actions)" >> $GITHUB_STEP_SUMMARY

        
